### ISSUE TITLE
[MINOR] FRAX Icon's transparency makes S4d vault clipped

### ISSUE THREAD

**Issue by timbotro** [Snowball-Finance/app-v2#160]
FRAX's transparent icon makes this vault look odd. 
![image](https://user-images.githubusercontent.com/89510251/130835986-50d77d53-97f5-4634-8b08-c31db00d248f.png)

If this is intentional, feel free to close.

**Comment by OxLuis** [comment]
Frax Icon Fixed

**Comment by timbotro** [comment]
Verified fixed
