### ISSUE TITLE
Retrying failed deposit race-condition

### ISSUE THREAD

**Issue by timbotro** [Snowball-Finance/app-v2#163]
It is difficult to reproduce, but i've had it happen a few times that after one of the two deposit operations have failed, for any reason, subsequent attempts fail with a JSON rpc error: 
``` 
message: "Error: VM Exception while processing transaction: reverted with reason string 'ERC20: transfer amount exceeds allowance'" .
```

**Comment by ghost** [comment]
Not sure what caused this, we reworked a lot of the contract calls so it's probably fixed already
